config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :task_lists
  resources :accounts
  get "all_accounts", to: "accounts#all_accounts", as: "all_accounts"
  resources :states, only: :index do 
    resources :counties, only: :index do
      resources :cities, only: :index
    end 
  end 
  resources :people
  root "todos#index"
  resources :todos
  
  get "/messages.html", to: "messages#index"
  get "/timezone", to: "people#timezone"
  
end

app/models/person.rb
class Person < ApplicationRecord
  # User.first.host_video
  store :settings, accessors: [ :host_video, :participants_video, :join_before_host ], code: JSON
  validates :first_name, length: {minimum: 2, maximum: 55}
  validates :last_name, length: {minimum: 2, maximum: 55}
  validates :email, format: { with: /\b[A-Z0-9._%a-z\-]+@example\.com\z/,
  message: "Enter a example.com email address" }
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end
  def timezone

  end 

  # GET /people/new
  def new
    @person ||= Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:first_name, :last_name, :email, :host_video, :participants_video, :join_before_host)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_with(model: person, local: true, html: {class: "card p-4"}) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <% if person.persisted? %>
    <div data-controller="save-input" class="form-group">
      <%= form.label :host_video %>
      <%= form.check_box :host_video, data: { target: "save-input.input_field", action: 'click->save-input#save_changes' } %>
    </div>

    <div data-controller="save-input" class="form-group">
      <%= form.label :participants_video %>
      <%= form.check_box :participants_video, data: { target: "save-input.input_field", action: 'click->save-input#save_changes' } %>
    </div>

    <div data-controller="save-input" class="form-group">
      <%= form.label :join_before_host %>
      <%= form.check_box :join_before_host, data: { target: "save-input.input_field", action: 'click->save-input#save_changes' } %>
    </div>
  <% end %>

  <div class="actions">
    <button class="btn btn-secondary">
      Create Person
    </button>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<div class='container'>
  <p id="notice"><%= notice %></p>

  <h1>People</h1>

  <table class="table">
    <thead>
      <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>Email</th>
        <th colspan="3"></th>
        <th>Poke?</th>
        <th>Pokes</th>
      </tr>
    </thead>

    <tbody>
      <% @people.each do |person| %>

        <tr>

          <td><%= person.first_name %></td>
          <td><%= person.last_name %></td>
          <td><%= person.email %></td>
          <td><%= link_to 'Show', person %></td>
          <td><%= link_to 'Edit', edit_person_path(person) %></td>
          <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>      
          <td>
            <div data-controller="example">
              <button type="button" data-id="<%= person.id  %>" data-reflex="click->ExampleReflex#poke">Poke</button>
              <button type="button" data-id="<%= person.id %>" data-reflex="click->ExampleReflex#unpoke">Unpoke</button>
            </div>
          </td>
          <td>
            <%= person.poke_count %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Person', new_person_path %>


  <div class="container">
    <div data-controller="hello">
      <input data-target="hello.name" type="text">
      <button data-action="click->hello#greet">Greet</button>
    </div>
  </div>
  <div data-controller="clipboard">
    Pin: <input type="text" value="1234" data-target="clipboard.source" readonly /> 
    <button class="clipboard-button" data-action="clipboard#copy">Copy to Clipboard</button>
  </div>
  <div data-controller="clipboard">
    PIN: <input data-target="clipboard.source" type="text" value="3737" readonly>
    <button data-action="clipboard#copy" class="clipboard-button">Copy to Clipboard</button>
  </div>
  <div class="animate__animated" data-controller="clipboard">
    Pin: <input data-target="clipboard.source" type="text" value="3737" readonly>
    <a href="#" data-action="clipboard#copy" class="clipboard-button">Copy to Clipboard</a>
  </div>


  <div class="col card p-5">
    <div data-controller="slideshow" data-slideshow-index="0" class="row">
    <div class="col-12">
      <button  class="btn btn-primary" data-action="slideshow#previous"><--</button>
      <button class="btn btn-primary" data-action="slideshow#next">--></button>
    </div>
      <div class="col ">
        <div data-target="slideshow.slide" class="slide animate__animated">🐵</div>
        <div data-target="slideshow.slide" class="slide animate__animated">🙈</div>
        <div data-target="slideshow.slide" class="slide animate__animated">🙉</div>
        <div data-target="slideshow.slide" class="slide animate__animated">🙊</div>
      </div>
    </div>
  </div>

</div>

app/views/people/new.html.erb
<div class="container">
  <h1>New Person</h1>

  <%= render 'form', person: @person %>

  <%= link_to 'Back', people_path %>

</div>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @person.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @person.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @person.email %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/people/timezone.html.erb
<div class="container">
  <div data-controller="time">
    <h1>Display Time</h1>
    <%= time_zone_select "time_zone", "time_zone", TZInfo::Timezone.all.sort, {include_blank: false}, {data: {target: 'time.time_zone', action: 'change->time#changed_zone'}} %>
    <h2 data-target="time.display_time">Time to Display</h2>
    <h3 data-target="time.display_time_zone">Time Zone to Display</h3>
    <div class="row">
      <button class="btn btn-primary" data-action="click->time#set_previous_time_zone">Previous Time Zone</button>
    </div>
  </div>

</div>