config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :task_lists
  resources :accounts
  get "all_accounts", to: "accounts#all_accounts", as: "all_accounts"
  resources :states, only: :index do 
    resources :counties, only: :index do
      resources :cities, only: :index
    end 
  end 
  resources :people
  root "todos#index"
  resources :todos
  
  get "/messages.html", to: "messages#index"
  get "/timezone", to: "people#timezone"
  
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :city
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :county
  has_many :accounts

  scope :name_asc, -> { order(name: :asc)  }
  scope :select_collection, -> { name_asc.map { |s| [s.name, s.id] }}
end

app/models/county.rb
class County < ApplicationRecord
  belongs_to :state
  has_many :cities

  scope :name_asc, -> { order(name: :asc)  }
    scope :select_collection, -> { name_asc.map { |s| [s.name, s.id, { url: Rails.application.routes.url_helpers.state_county_cities_path(state_id: s.state_id, county_id: s.id) }] }}

end

app/models/person.rb
class Person < ApplicationRecord
  # User.first.host_video
  store :settings, accessors: [ :host_video, :participants_video, :join_before_host ], code: JSON
  validates :first_name, length: {minimum: 2, maximum: 55}
  validates :last_name, length: {minimum: 2, maximum: 55}
  validates :email, format: { with: /\b[A-Z0-9._%a-z\-]+@example\.com\z/,
  message: "Enter a example.com email address" }
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
  has_many :counties

  scope :name_asc, -> { order(name: :asc)  }
  scope :select_collection, -> { name_asc.map { |s| [s.name, s.id, { url: Rails.application.routes.url_helpers.state_counties_path(s) }] }}
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :task_list
end

app/models/task_list.rb
class TaskList < ApplicationRecord
  has_many :tasks, dependent: :destroy
  accepts_nested_attributes_for :tasks, allow_destroy: true, reject_if: proc { |attr| attr['description'].blank? }
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :description, presence: true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
    render partial: 'accounts/index', assigns: { accounts: @accounts }
  end

  def all_accounts
  end 

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:name, :city_id)
    end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    state = State.find(params[:state_id])
    county = state.counties.find(params[:county_id])
    cities = county.cities
    render json: cities.select_collection
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end
  def timezone

  end 

  # GET /people/new
  def new
    @person ||= Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:first_name, :last_name, :email, :host_video, :participants_video, :join_before_host)
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
    @todo ||= Todo.new # Regular CRUD will call Todo.new, otherwise from reflex, @todo
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:description, :completed_at)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/counties_helper.rb
module CountiesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/task_lists_helper.rb
module TaskListsHelper
end

app/views/todos/_form.html.erb
<div class="container">
  <%= form_with(model: todo, local: true) do |form| %>
    <% if todo.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

        <ul>
        <% todo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_field :description, class: 'form-control', data: { reflex: "change->ExampleReflex#form" } %>
    </div>

    <div class="form-group">
      <% if todo.persisted? %>
        <div class="float-right">
          <%= link_to 'Destroy', todo, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } %>
        </div>
      <% end %>

      <%= form.submit class: 'btn btn-primary' %>

      <% if todo.persisted? %>
        <%= link_to "Cancel", todo, class: "btn btn-link" %>
      <% else %>
        <%= link_to "Cancel", todos_path, class: "btn btn-link" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/todos/edit.html.erb
<h1>Edit Todo</h1>

<%= render 'form', todo: @todo %>

app/views/todos/index.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-sm-6">
      <h1>Todos</h1>
    </div>

    <div class="col-sm-6 text-right">
      <%= link_to new_todo_path, class: 'btn btn-primary' do %>
        Add New Todo
      <% end %>
    </div>
  </div>

  <%= render "todos/form", todo: @todo %>

  <div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
          <th></th>
          <th>Description</th>
          <th>Completed at</th>
          <th></th>
        </tr>
      </thead>

      <tbody >
        <% @todos.each do |todo| %>
          <%= content_tag :tr, id: dom_id(todo), class: dom_class(todo) do %>
            <td><%= check_box_tag nil, nil, todo.completed_at?, data: { reflex: "click->ExampleReflex#toggle", id: todo.id } %></td>
            <td><%= todo.description %></td>
            <td><%= todo.completed_at %></td>
            <td><%= link_to 'Show', todo %></td>
            <td><%= link_to 'Delete', "#!", data: { reflex: "click->ExampleReflex#delete", id: todo.id } %></td>
            <td><%= link_to 'Edit', "#!", data: { controller: "example", action: "click->example#startEdit", id: todo.id } %></td>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>

</div>

app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render 'form', todo: @todo %>

app/views/todos/show.html.erb
<div class="page-header">
  <%= link_to todos_path, class: 'btn btn-default' do %>
    All Todos
  <% end %>
  <%= link_to edit_todo_path(@todo), class: 'btn btn-primary' do %>
    Edit
  <% end %>
  <h1>Show todo</h1>
</div>

<dl class="dl-horizontal">
  <dt>Description:</dt>
  <dd><%= @todo.description %></dd>

  <dt>Completed at:</dt>
  <dd><%= @todo.completed_at %></dd>

</dl>