config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :task_lists
  resources :accounts
  get "all_accounts", to: "accounts#all_accounts", as: "all_accounts"
  resources :states, only: :index do 
    resources :counties, only: :index do
      resources :cities, only: :index
    end 
  end 
  resources :people
  root "todos#index"
  resources :todos
  
  get "/messages.html", to: "messages#index"
  get "/timezone", to: "people#timezone"
  
end

app/models/task_list.rb
class TaskList < ApplicationRecord
  has_many :tasks, dependent: :destroy
  accepts_nested_attributes_for :tasks, allow_destroy: true, reject_if: proc { |attr| attr['description'].blank? }
end

app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController
  before_action :set_task_list, only: [:show, :edit, :update, :destroy]

  # GET /task_lists
  # GET /task_lists.json
  def index
    @task_lists = TaskList.all
  end

  # GET /task_lists/1
  # GET /task_lists/1.json
  def show
  end

  # GET /task_lists/new
  def new
    @task_list = TaskList.new
  end

  # GET /task_lists/1/edit
  def edit
  end

  # POST /task_lists
  # POST /task_lists.json
  def create
    @task_list = TaskList.new(task_list_params)

    respond_to do |format|
      if @task_list.save
        format.html { redirect_to @task_list, notice: 'Task list was successfully created.' }
        format.json { render :show, status: :created, location: @task_list }
      else
        format.html { render :new }
        format.json { render json: @task_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /task_lists/1
  # PATCH/PUT /task_lists/1.json
  def update
    respond_to do |format|
      if @task_list.update(task_list_params)
        format.html { redirect_to @task_list, notice: 'Task list was successfully updated.' }
        format.json { render :show, status: :ok, location: @task_list }
      else
        format.html { render :edit }
        format.json { render json: @task_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_lists/1
  # DELETE /task_lists/1.json
  def destroy
    @task_list.destroy
    respond_to do |format|
      format.html { redirect_to task_lists_url, notice: 'Task list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task_list
      @task_list = TaskList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_list_params
      params.require(:task_list).permit(:name, tasks_attributes: [:_destroy, :id, :description])
    end
end

app/helpers/task_lists_helper.rb
module TaskListsHelper
end

app/views/task_lists/_form.html.erb
<div class="container">
  <%= form_with(model: task_list, local: true) do |form| %>

    <% if task_list.errors.any? %>

      <div id="error_explanation">
        <h2><%= pluralize(task_list.errors.count, "error") %> prohibited this task_list from being saved:</h2>

        <ul>
          <% task_list.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <h1>Tasks</h1>
    <div data-controller="nested-form">
      <template data-target="nested-form.template">
        <%= form.fields_for :tasks, Task.new, child_index: 'TEMPLATE_RECORD' do |task| %>
          <%= render 'task_fields', form: task %>
        <% end %>
      </template>
      <%= form.fields_for :tasks do |task| %>
        <%= render 'task_fields', form: task %>
      <% end %>
      <div data-target="nested-form.add_item">
        <%= link_to "Add Task", "#", data: {action: "nested-form#add_association" }%>
      </div>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/task_lists/_task_fields.html.erb
<div class="nested-fields">
  <div class="form-group">
    <%= form.hidden_field :_destroy %>
    <%= form.text_field :description, placeholder: "Description", class: "form-control" %>
    <small>
      <%= link_to "Remove", "#", data: { action: "click->nested-form#remove_association" } %> 
    </small>
  </div>
</div>

app/views/task_lists/edit.html.erb
<h1>Editing Task List</h1>

<%= render 'form', task_list: @task_list %>

<%= link_to 'Show', @task_list %> |
<%= link_to 'Back', task_lists_path %>

app/views/task_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Task Lists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @task_lists.each do |task_list| %>
      <tr>
        <td><%= task_list.name %></td>
        <td><%= link_to 'Show', task_list %></td>
        <td><%= link_to 'Edit', edit_task_list_path(task_list) %></td>
        <td><%= link_to 'Destroy', task_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task List', new_task_list_path %>

app/views/task_lists/new.html.erb
<h1>New Task List</h1>

<%= render 'form', task_list: @task_list %>

<%= link_to 'Back', task_lists_path %>

app/views/task_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task_list.name %>
</p>

<%= link_to 'Edit', edit_task_list_path(@task_list) %> |
<%= link_to 'Back', task_lists_path %>